### PR TITLE
Test against Moments.py descriptors

### PR DESCRIPTION
**Pull request by bp-kelley**
These fail, but may be a decent start for you

### CODE REVIEW

**Comment by greglandrum** [comment]
The problem here is that the python script calls AddHs before generating the moments. This changes everything.

The attached file demonstrates that the current C++ generates the same results as the python when called on the same input.
[Moments.py.txt](https://github.com/greglandrum/rdkit/files/719865/Moments.py.txt)

**Comment by bp-kelley** [comment]
Odd, my tests also calls AddHs but has different results.

**Comment by bp-kelley** [comment]
Ah, the H's didn't have 3d I expect.

**Comment by greglandrum** [comment]
Yeah, you have to set coordinates like in the Python file

**Pull request merged**
