### PR TITLE
Feat/add cistrans dbl bonds

### PR DESCRIPTION
**Pull request by coleb**
C++ and Python test cases for Bond::setStereo with STEREOCIS and STEREOTRANS. 

I think the only thing left we still need is Bond::setStereoAtoms(int bgnIdx, int endIdx). Want to add that? or shall I?

### CODE REVIEW

**Comment by greglandrum** [comment]
I'd love to get the PR instead of having to do it myself. :-)

**Comment by coleb** [comment]
I'll make it tomorrow's train-ride project.

**Comment by coleb** [comment]
Should be finished now. Let me know if you want me to rebase the branch to
not include the merge of origin/master. Theoretically the pull request
against main master branch won't be as verbose as the one on your repo.

-Brian

**Comment by greglandrum** [comment]
Yeah, the problem here is that my version of master is super out-of-date. I'll update my branch against origin/master and you can do the PR against that.

**Pull request merged**
